version: '3.9'
services:
  #MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
  #Node API service
  api:
    build: .
    ports:
      - 4000:3000
    environment:
      NODE_ENV: evelopment
      PORT: 3000
      MONGODB_URI: mongodb://db_container:27017/yesinvest
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}




